### PR TITLE
sending back the correct admin response

### LINKED ISSUE #130: Instructor answering a question does not work. it always says the answer is incorrect

### PR DESCRIPTION
**Pull request by ahmedqarmout2**
fixes #130

### CODE REVIEW

File: server/questions.js [hunk 1]
```diff
@@ -199,7 +199,7 @@ exports.checkAnswer = function(questionId, user, answer, callback) {
 		var value = (answer === question.answer);
 
 		if (userType === common.userTypes.ADMIN) {
-			return callback(null, value);
+			return callback(null, {correct: value, points: question.points});
```
Comment (ahmedqarmout2) [inline server/questions.js:202]: Do we want to return 0 points for the proof?

**Review by esteeroramy — APPROVED** [review]

File: server/questions.js (hunk 1 above)
Comment (esteeroramy) [reply server/questions.js:202]: It should not matter since we won't be using it for anything
